### ISSUE TITLE
Hardcoded Lambda role ARN

### ISSUE THREAD

**Issue by paulwakeford** [sirceljm/aws-lambda-blog#1]
Hi,

Is this a good idea?

> lambda_role: "arn:aws:iam::128137337832:role/optiprocure_auth",

In LambdaBlogPlatform/lambdas/webpack_single.config.js

**Comment by sirceljm** [comment]
Definitely not! I will change it to dynamic. It is just a plugin to quickly update a lambda function from Sublime Text though.

**Comment by sirceljm** [comment]
Done d5cd07f253fd4937921991dd9810fe3754afbbb5
