### ISSUE TITLE
Any way to trim down the IAM permissions?

### ISSUE THREAD

**Issue by paulwakeford** [sirceljm/aws-lambda-blog#2]
I'm a little nervous about anything granting itself

		"arn:aws:iam::aws:policy/AWSLambdaFullAccess",
		"arn:aws:iam::aws:policy/AmazonS3FullAccess",
		"arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess",
		"arn:aws:iam::aws:policy/AmazonSESFullAccess"

.. so it can delete any/all buckets and DDB tables. 

Thanks,

Paul

**Comment by sirceljm** [comment]
I agree. I will change it to Inline policies.

**Comment by sirceljm** [comment]
1474863e88ebc2e3580bdcf73fd5b2701c41459c Full access permissions are no longer used
