### ISSUE TITLE
Trying to install - readme out of date?

### ISSUE THREAD

**Issue by paulwakeford** [sirceljm/aws-lambda-blog#3]
Do I save the credentials json file as credentials.csv (that looks to be what install.js wants?)

I don't have install_config_template.js or install_config.js

Can I use an existing ACM ARN?

Unsure how to proceed here...latest updates mention a wizard?

Thanks,

Paul

**Comment by sirceljm** [comment]
I made some changes to the install.js so that it makes everything for you. I will update the readme as well soon.

You make a new user the same as before. Make sure that you check "programmatic access". Then just click next until the last step. On the last step, you will have a button "Download .csv file" click that and save the file in your LambdaBlogPlatform folder (or elsewhere and then enter the path in the installer).

The wizard will then say that user doesn't have permissions. For that you have to make the inline policy (Click on your user in AWS IAM -> Add inline policy -> Custom Policy -> Select) with: 

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1481118325000",
            "Effect": "Allow",
            "Action": [
                "iam:CreatePolicy",
                "iam:CreateRole",
                "iam:GetPolicy",
                "iam:GetRole",
                "iam:AttachUserPolicy",
                "iam:AttachRolePolicy",
                "iam:PassRole",
                "route53:ListHostedZones",
                "acm:ListCertificates"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```

You can name the policy whatever you like.

Hope this helps. Please let me know how the installation went fo you.

**Comment by sirceljm** [comment]
For the certificate. 
The certificate has to have the same name as your domain or if you want to use LambdaBlogPlatform on the subdomain you can make the certificate with name *.domain.com. The installer will look at all the certificates that are appropriate and will list them for you to select.

**Comment by paulwakeford** [comment]
OK, some progress. I got the credentials file in the correct format, and realised that this doesn't support profiles so set my default profile to be the AWS account I want to use for this - however 

node install.js

.. produces no output but also does not return. Looking in install.js I'm expecting to be prompted for my region.

**Comment by sirceljm** [comment]
Did you change the install.js file? This could happen if the script is waiting for some asynchronous callback but that callback doesn't happen. 

Do you get prompted to enter the prefix, but it doesn't go forward after that? The regions are just a static JSON object and after the prefix prompt, there should be no other obstacles to show that question.

**Comment by ashutoshvct** [comment]
I made changes in the install.js file, I just commented out the mumbai region and now it gives no output. 
Same issue that @paulwakeford has.
My instance in which I pull the git repo is in mumbai region and my Email forwarding is in US-EAST region.
Using Node version 4.3, Ubuntu 16
Also, when I did npm install i get this error:

> node-pre-gyp: ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.2-node-v48-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.2 and node@6.10.0 (node-v48 ABI) (falling back to source compile with node-gyp)

**Comment by ashutoshvct** [comment]
I think this only works on windows instance.

**Comment by sirceljm** [comment]
Can you please post the file you changed. I tried it on linux as well and the error message you posted is nothing to be concerned about. It is just saying that the precompiled binary for zopfli for linux couldn't be found. In my case it then builds it from source. Can you please also post the whole output when you run npm install.

**Comment by ashutoshvct** [comment]
I just commented out the Mumbai region and installed it. Now, it gives me nothing (no output).
