### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by saempyla** [sirceljm/aws-lambda-blog#4]
Hi!
Im trying to install with Ubuntu 16.04.02 but I ran to errors in npm install:
npm WARN Blog@1.0.0 No repository field.
npm WARN Blog@1.0.0 No license field.

Any tips?

**Comment by sirceljm** [comment]
Hi,

these are just warnings (http://stackoverflow.com/questions/34020746/npm-warn-package-json-stock0-0-1-no-repository-field) you should probably just continue with the installation. Did the packages install to the node_modules folder?

**Comment by ashutoshvct** [comment]
I made changes in the install.js file, I just commented out the mumbai region and now it gives no output.
Same issue that @paulwakeford has.
My instance in which I pull the git repo is in mumbai region and my Email forwarding is in US-EAST region.
Using Node version 4.3, Ubuntu 16
Also, when I did npm install i get this error:

> node-pre-gyp: ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.2-node-v48-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.2 and node@6.10.0 (node-v48 ABI) (falling back to source compile with node-gyp)

**I think it works on Windows only.**

**Comment by ashutoshvct** [comment]
It doesn't work. When I do node install, it gets stuck.
Do I have to wait longer than 15 mins?

**Comment by pblanton** [comment]
Here is my failure with node.install...

_module.js:472
    throw err;
    ^

Error: Cannot find module 'unhandled-rejection'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/myname/projects/aws-lambda-blog/install.js:4:26)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)_

The line it's complaining about in install.js is: 

    var unhandledRejection = require("unhandled-rejection");

I manually installed it:

myname@ubuntu:~/projects/aws-lambda-blog$ sudo npm install -g unhandled-rejection
+ unhandled-rejection@1.0.0
added 3 packages in 2.361s

Still fails with the same error.

I have copied the install_config_template.js to install_config.js and configured the values in there.

Any ideas?

**Comment by sirceljm** [comment]
Try npm install unhandled-rejection

**Comment by pblanton** [comment]
LOL. You caught me while I was updating the question. I did that and then had to do it again without the -g option, then re-run npm install, and now it seems to be doing something.

**Comment by pblanton** [comment]
I do still get four warnings when running npm install...

myname@ubuntu:~/projects/aws-lambda-blog$ sudo npm install
npm WARN Blog@1.0.0 No repository field.
npm WARN Blog@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

But it seems like it's doing something. At least it's not failing straight away.

**Comment by sirceljm** [comment]
This should be ok. Try node install.js if you get the prompt from the wizard.

**Comment by pblanton** [comment]
Thanks Matej. I didn't get the wizard, but I suspect that's because I pre-answered all questions in install_config.js. It's still sitting there... I presume doing something.

I checked my AWS console and I don't see any new S3 buckets or API gateway objects, so I'll just keep waiting.

**Comment by sirceljm** [comment]
You should be getting some output. What commands did you run for install?

**Comment by pblanton** [comment]
sudo node install.js

It never did anything. It's still just sitting there.

**Comment by sirceljm** [comment]
Try upgrading node to version 6. That might be the problem.

**Comment by ashutoshvct** [comment]
I have used node 6.11.1. Please, can you try to install it on ubuntu machine or give us the zip file code in lambda?

**Comment by sirceljm** [comment]
I tried installing it on linux Ubuntu 16.04 and it installed ok for me. I uncomented Mumbai in the install.js and then run the script.

```
matej@matej-XPS-15-9560:~/aws-lambda-blog$ node install
? File credentials.csv with required credentials was not found in this folder. Press Enter to refresh or enter path: /media/matej/DATASHU
R/iam/lbp.csv
? Prefix for this installation Awly
? In which region do you want to install? Asia Pacific (Mumbai) - ap-south-1
? Which hosted zone will you be using for this installation? (If you want to use a subdomain, you will be able to configure that on the n
ext step) awly.io
? Enter a subdomain or leave blank if you want to use just your domain mumbai.awly.io
? Choose certificate *.awly.io - arn:aws:acm:us-east-1:128137337832:certificate/54599b46-2aa2-4f84-a833-74321f0e7b80
? API Gateway stage name prod
? Admin password mumbai
? Email address for contact form - you have to validate it in AWS SES xxxxxxx@gmail.com
? OPTIONAL - ReCaptcha site key - you can skip this & edit later in API gateway stage variables 
? OPTIONAL - ReCaptcha private key - you can skip this & edit later in API gateway stage variables 
? OPTIONAL - Disqus subdomain (______.disqus.com) you can skip this & edit later in API gateway stage variables 

AWS Lambda Blog Platform install

Getting user account ID

Creating policies

Waiting 5s for changes to propagate

Attaching policy to the user
Policy: Awly_install_policy was attached to the user: lbp

creating IAM role
EntityAlreadyExists: Role with name Awly_role already exists.

Attaching policy to the role
Policy: arn:aws:iam::128137337832:policy/Awly_role_policy was attached to the role: Awly_role

Waiting 10s for changes to propagate

Creating S3 bucket
S3 bucket: awly-mumbai.awly.io was created

Configuring S3 bucket for website hosting
S3 bucket: awly-mumbai.awly.io was configured for website hosting

Uploading files to S3 bucket
no new files found

Creating DynamoDB tables
Table: Awly_objects was created
Table: Awly_posts was created

Populating DynamoDB tables with data
An item was added into: Awly_objects table
An item was added into: Awly_objects table
An item was added into: Awly_objects table
An item was added into: Awly_posts table

Uploading Lambda functions & creating API gateway endpoints
Creating lambda function: Awly_about
Creating lambda function: Awly_contact
Creating lambda function: Awly_get
Creating lambda function: Awly_getPost
Creating lambda function: Awly_getPostsByCategory
Creating lambda function: Awly_listPosts
Creating lambda function: Awly_login
Creating lambda function: Awly_rss
Creating lambda function: Awly_sendMessage
Creating lambda function: Awly_addCategory
Creating lambda function: Awly_deletePost
Creating lambda function: Awly_editCategory
Creating lambda function: Awly_getCategories
Creating lambda function: Awly_getPostAdmin
Creating lambda function: Awly_getSettings
Creating lambda function: Awly_getTemplates
Creating lambda function: Awly_listPostsAdmin
Creating lambda function: Awly_moveCategory
Creating lambda function: Awly_publishPost
Creating lambda function: Awly_removeCategory
Creating lambda function: Awly_setSettings
Creating lambda function: Awly_unpublishPost
Creating lambda function: Awly_uploadImage
Creating lambda function: Awly_uploadPost
Creating lambda function: Awly_uploadTemplateImage

API Gateway: Awly was created

Configuring cloudfront

Adding Route53 record

DONE!
Please wait around 15 minutes for changes to propagate.
Your admin password is: mumbai you can change it in API Gateway -> your API -> stages -> prod -> Stage variables
matej@matej-XPS-15-9560:~/aws-lambda-blog$ node --version
v8.2.1
matej@matej-XPS-15-9560:~/aws-lambda-blog$ npm --version
5.3.0
matej@matej-XPS-15-9560:~/aws-lambda-blog$ uname -r
4.8.0-58-generic
matej@matej-XPS-15-9560:~/aws-lambda-blog$ uname -a
Linux matej-XPS-15-9560 4.8.0-58-generic #63~16.04.1-Ubuntu SMP Mon Jun 26 18:08:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
matej@matej-XPS-15-9560:~/aws-lambda-blog$ 
```

I really don't know how to help you further. Can you give me some more detail about what you changed or at which stage does the install fail.

**Comment by ashutoshvct** [comment]
Let me give this a shot.
I get this error:

> ? File credentials.csv with required credentials was not found in this folder. Press Enter to refresh or enter path: 
> >> File credentials.csv was not found. Please retry.

I'm using IAM role so I don't require credentials.CSV, right?

The issue is now solved, I created a user with the inline policy. I think there must be some changes made to the code so that it can accept roles.

**Comment by ashutoshvct** [comment]
Also, the install.js attaches SSL in CloudFront, so would I be charged $600/MO?

> Dedicated IP Custom SSL
You pay $600 per month for each custom SSL certificate associated with one or more CloudFront distributions using the Dedicated IP version of custom SSL certificate support. This monthly fee is prorated by the hour. For example, if you had your custom SSL certificate associated with at least one CloudFront distribution for just 24 hours (i.e. 1 day) in the month of June, your total charge for using the custom SSL certificate feature in June will be (1 day / 30 days) * $600 = $20. For other SSL options, please visit the CloudFront Custom SSL detail page. 

I think SNI SSL is free. Can you please confirm?

**Comment by sirceljm** [comment]
You don't have to get the dedicated IP certificate for aws-lambda-blog just select the standard certificate from AWS in your cloudfront distribution.

**Comment by pblanton** [comment]
ashutoshvct,

That $600/mo. charge is ONLY if you ABSOLUTELY MUST have a dedicated IP address for your SSL Certificate. The only reason to do so is if your clients cannot use SNI (Server Name Indication). All modern browsers can.

You only need the $600/mo. dedicated IP cert if you absolutely need to serve clients using IE on Windows XP, or anyone on a very old version of Android on old hardware.

The point is that IPV4 IP addresses are running out and Amazon is doing their part to ensure that nobody uses one unless they ABSOLUTELY MUST; and if they do, then Amazon will increase the pain until they choose not to.
